apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/vmaltsev-tech/platform-repo.git
    path: infra/apps/gateway
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
