apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-namespaces
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/vmaltsev-tech/platform-repo.git
    path: infra/apps/namespaces
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
